### ISSUE TITLE
Convert `src/react` into a minimalist template

### ISSUE THREAD

**Issue by MangelMaxime** [elmish/templates#11]
The goal of this template will be to help quick start a project.

In my opinion the project need to contain:

- Basic webpack configuration (only the part needed to run Fable, no SASS)
- Minimal application with:
  - Main application handling the Navigation
  - One sub module to show the project structure
  - No debugger support (user will need to add it later if he want to use it ?) This will avoid problem with people asking why there are errors in the console when starting the app for the first time.

@forki @et1975 What is your opinion guys ?

**Comment by alfonsogarciacaro** [comment]
I haven't used them yet, but it'd be nice to use template conditionals yo opt-in for several features when starting the template, instead of maintaining different templates.

**Comment by alfonsogarciacaro** [comment]
That's mainly for things like the debugger.  I agree that probably external loaders like SASS can be removed. Users who want and know how to use them won't have problems to add them to the webpack config by themselves.

**Comment by et1975** [comment]
Does dotnet templating offer "features" options?

**Comment by MangelMaxime** [comment]
@et1975 Seems like yes.
https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/

**Comment by MangelMaxime** [comment]
Another question, when updating the template I would like to use Fake to abstract the build process. (something like what I did here https://github.com/fable-compiler/Fable/pull/1011).

Should I ? What is your opinion ?

**Comment by et1975** [comment]
My 2c:
fake build of the template? Yes
fake build of the template-created project? Yes

**Comment by CaringDev** [comment]
Being a F# (C#) developer and not having much (modern) web experience *I really like the template*. Removing fluff is easier than adding (NuGet vs. npm, webpack config). I'd at least keep the current template (with a different name?).

**Comment by MangelMaxime** [comment]
@CaringDev The idea is having `Fable.Template.Elmish.React` as slim as possible so people can start with it from scratch if they want.

And you will still have `Fable.Template.Elmish.React.Demo` with all the features and example already plug in. 

So I think this should be ok ?

**Comment by CaringDev** [comment]
@MangelMaxime Yes, true. Also, from a maintenance perspective less templates are better. :+1:

**Comment by reinux** [comment]
Did the two templates get merged recently or something? Because `React` is a lot more involved than I remember it being.

Personally, I liked starting off with a barebones template and then moving things in from `Demo` or whatever else whenever I needed that some functionality.

**Comment by MangelMaxime** [comment]
Last publish of the template was 7 months ago

![image](https://user-images.githubusercontent.com/4760796/94014440-d13ea500-fdab-11ea-8ccd-25e759cf43ab.png)

I think this update was to upgrade to latest Fable version and stuff like that. I don't think we made a change to the functionalities etc. If needed, you can try to take a look at the Git history.

**Comment by reinux** [comment]
Weird... I could have sworn the template used to be a lot simpler -- no SASS etc, [as you noted](https://github.com/elmish/templates/issues/11#issue-235021424), just a one-page up/down counter demo, no .sln.

I must be mistaken about something.

**Comment by reinux** [comment]
Turns out I was using [Semuserable.Fable.Templates](https://github.com/semuserable/Semuserable.Fable.Templates). My bad.

**Comment by MangelMaxime** [comment]
I am closing this issue because it has been open for 3 years and I don't think it will ever happen.
