### ISSUE TITLE
Support of the latest Node and Webpack version

### ISSUE THREAD

**Issue by bastian-nolte** [elmish/templates#131]
### Problem description:
"yarn install" aborts with an error.

### System: 

- macOS Monterey, version 12.5
- node v18.7.0
- node-gyp v3.8.0
- npm 8.15.0

### How to recreate the problem?
```bash
dotnet new -i Fable.Template.Elmish.React.Demo
dotnet new fable-elmish-react-demo -n awesomeDemo -lang f#
cd awesomeDemo
yarn install
```

#### Error Message
`error …/node_modules/node-sass: Command failed.`

### Analysis:
Updating the NPM and NuGet dependencies in the two template packages and migrating the Webpack configurations to the latest version 5 should satisfy the requirement and fix the issue.

Remark:
I will submit a pull request shortly.

**Comment by bastian-nolte** [comment]
I think the pull request still needs some adjustment work regarding Saas and Fortawesome. I will deal with it in the next few days.

**Comment by MangelMaxime** [comment]
Thank you, I just released a new version of both packages
