### ISSUE TITLE
Uppercase fields in records

### ISSUE THREAD

**Issue by forki** [elmish/templates#3]
In Types.fs we have things like currentPage in lowercase. that's not really idiomatic in F#.

**Comment by MangelMaxime** [comment]
I think @et1975 told me the reason is is because he wanted to follow the JavaScript convention here as it's on the client side.
But he will probably explain better than me.

Personnaly, in my projects I prefer to user Uppercase fields.

**Comment by forki** [comment]
We're not doing Javascript.

**Comment by et1975** [comment]
I might be in minority in this one, but every ML (and most other languages really) uses lowerCase for record fields, whereas F# guidelines were driven by .NET, and let's be honest, VB - compatibility. But fable doesn't interop with C#, the fields are actual fields (not properties) and if we do interop it's with JS where the conventions are lowerCase. 
Personally, want to get inline with the rest of the languages on this, but @MangelMaxime it's up to you what you do in the template, I'll keep using lowerCase and I believe I have Don's and Alfonso's blessing on this one.

**Comment by forki** [comment]
Ok let's postpone this one. It's not easy. 

One thing we definitely should do is improve the fslint. 

Anyways in order to make "Isomorphic F#" a thing we should decide on this at some point.

**Comment by MangelMaxime** [comment]
Let's keep it as it is now.

We will be able to change it later if needed :)

**Comment by alfonsogarciacaro** [comment]
@forki Kzrys announced at fsharpX that now it's possible to configure FSharpLint to disable some of the naming rules `RecordFieldNamesMustBePascalCase` selectively: http://fsprojects.github.io/FSharpLint/NameConventions.html

**Comment by forki** [comment]
No that's the correct one. Seriously.

Am 18.04.2017 3:05 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by MangelMaxime** [comment]
After discussion, on the gitter channel with @forki, we will follow the *idiomatic F# syntax*.

This will first occur into the `react-demo` template and will be reflected later in the `react` template which will be made minimalist to simply quick start a new project. (Folders architecture, minimal webpack settings, etc).

`react-demo` is a template dedicated to show Elmish when doing talks and so on.
