### ISSUE TITLE
Add a sample of how to reference a JS React component in the template

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/templates#5]
Somehow related to: https://github.com/fable-elmish/elmish/issues/89

It'll be helpful for users to know how they can use React components downloaded as npm packages (a calendar, etc).

[Example](https://github.com/fable-compiler/fable-electron/blob/64746c082daa522b7a99ec46e1d4205359435429/samples/material-ui/src/renderer.fsx#L50-L53)

**Comment by MangelMaxime** [comment]
I am not sure it should be placed in the template. The current template should just kick start a project using Elmish. I added bulma in it mostly to have the scss loader configured and also because I don't like template/sample looking not polish :)

But having it in a sample + on the docs site make senses :)

**Comment by alfonsogarciacaro** [comment]
Having a sample of how to interact in general with external components (either React or non-React as @whitetigle did with Leaflet) will work as well :+1: It'd be nice if the template README had also a link to that sample.

**Comment by whitetigle** [comment]
I can prepare a simple sample with leaflet based on what I just did if you wish?

**Comment by MangelMaxime** [comment]
Yes sure :)
If you want I can create a repo to host it under fable-elmish org.

**Comment by whitetigle** [comment]
ok!

**Comment by MangelMaxime** [comment]
What should be the name of the repo ?

Something like:
- sample-react-leaflet 
- sample-react-external-component

I am more in favor of the second as it's more generic :)

**Comment by alfonsogarciacaro** [comment]
My vote goes for the generic version too :+1:

**Comment by MangelMaxime** [comment]
Repo created [here](https://github.com/fable-elmish/sample-react-external-component)

**Comment by whitetigle** [comment]
Question: do I start from the template?

**Comment by MangelMaxime** [comment]
I would say yes because everything is wired. And you have some basic styling available 😊.

**Comment by MangelMaxime** [comment]
The sample requested in this issue should go into the `src/react-demo` template.

**Comment by kerams** [comment]
Any progress on this? :)

**Comment by whitetigle** [comment]
Oops... Sorry. None yet. Apart leaflet/mapbox I have not used any other react component though. I am going to see what I can do.

**Comment by jonkelling** [comment]
you can check out my [repo](http://github.com/jonkelling/FableApp) here for some help, @whitetigle. See components. Otherwise, @MangelMaxime @kermas I'd be up for contributing to this unless someone else already took it on.

**Comment by MangelMaxime** [comment]
@jonkelling As far I know, no one is working on this.

If you want to send a PR you can :)

**Comment by MangelMaxime** [comment]
Closing as I don't think it will happen. 

People can take a look at [SAFE Documentation](https://safe-stack.github.io/docs/recipes/javascript/third-party-react-package/) if needed.
