### ISSUE TITLE
replace paket.exe with latest bootstrap version

### ISSUE THREAD

**Issue by spaceywolfi** [elmish/templates#51]
i had an issue with updating packages: https://github.com/fsprojects/Paket/issues/3291

the problem is that the paket.exe file is outdated. i think it is recommended to use the bootstrap version of paket to enable paket to update itself. https://github.com/fsprojects/Paket/releases/tag/5.174.2

:+1:

**Comment by alfonsogarciacaro** [comment]
Thanks for pointing that out @spaceywolfi! Would it be possible to send a PR for that?

**Comment by spaceywolfi** [comment]
@alfonsogarciacaro yes will do :)

**Comment by spaceywolfi** [comment]
#52
