### ISSUE TITLE
Update to Fable 2.1

### ISSUE THREAD

**Issue by kunjee17** [elmish/templates#54]
I have recently created a project using this template. I guess things are pretty much on old Fable. It would be great to update to Fable 2.0.

**Comment by MangelMaxime** [comment]
It should be updated to Fable 2.1

**Comment by MangelMaxime** [comment]
Would you want to send a PR as you probbaly updated your own project :) ?

**Comment by kunjee17** [comment]
I took the minimal sample project as of now. If it is ok to wait I ll put it in todo list and do it later this month.

**Comment by kunjee17** [comment]
Thanks @MangelMaxime . You are awesome.
